name: expandify
description: Provides widget to help child expand to fill space or scroll
version: 1.0.2
homepage: https://github.com/rmtmckenzie/expandify

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0